# Generated by Django 3.2.25 on 2025-11-11 18:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255, verbose_name='Punkt początkowy')),
                ('end_location', models.CharField(max_length=255, verbose_name='Punkt docelowy')),
                ('intermediate_stops', models.JSONField(blank=True, default=list, verbose_name='Punkty pośrednie')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(verbose_name='Godzina')),
                ('available_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Liczba dostępnych miejsc')),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena za miejsce (udział w kosztach)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Przejazd',
                'verbose_name_plural': 'Przejazdy',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
