# Generated by Django 5.2.8 on 2026-01-13 19:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255, verbose_name='Punkt początkowy')),
                ('end_location', models.CharField(max_length=255, verbose_name='Punkt docelowy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ulubiona trasa',
                'verbose_name_plural': 'Ulubione trasy',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'start_location', 'end_location')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255, verbose_name='Punkt początkowy')),
                ('end_location', models.CharField(max_length=255, verbose_name='Punkt docelowy')),
                ('intermediate_stops', models.JSONField(blank=True, default=list, verbose_name='Punkty pośrednie')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(verbose_name='Godzina')),
                ('available_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Liczba dostępnych miejsc')),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena za miejsce (udział w kosztach)')),
                ('completed', models.BooleanField(default=False, verbose_name='Zakończony')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Przejazd',
                'verbose_name_plural': 'Przejazdy',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('reserved', 'Zarezerwowane'), ('accepted', 'Zaakceptowane'), ('paid', 'Opłacone'), ('cancelled', 'Anulowane')], default='reserved', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data opłacenia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('trip', 'passenger')},
            },
        ),
        migrations.CreateModel(
            name='TripTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Moja trasa', max_length=255, verbose_name='Nazwa szablonu')),
                ('start_location', models.CharField(max_length=255, verbose_name='Punkt początkowy')),
                ('end_location', models.CharField(max_length=255, verbose_name='Punkt docelowy')),
                ('intermediate_stops', models.JSONField(blank=True, default=list, verbose_name='Punkty pośrednie')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Godzina')),
                ('available_seats', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Liczba dostępnych miejsc')),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena za miejsce')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Szablon przejazdu',
                'verbose_name_plural': 'Szablony przejazdów',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_role', models.CharField(choices=[('driver', 'Kierowca'), ('passenger', 'Pasażer'), ('both', 'Oba')], default='both', max_length=20, verbose_name='Preferowana rola')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numer telefonu')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Zdjęcie profilowe')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Powiadomienia włączone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil użytkownika',
                'verbose_name_plural': 'Profile użytkowników',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfel',
                'verbose_name_plural': 'Portfele',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Treść wiadomości')),
                ('read', models.BooleanField(default=False, verbose_name='Przeczytane')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.booking', verbose_name='Rezerwacja')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Odbiorca')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Nadawca')),
            ],
            options={
                'verbose_name': 'Wiadomość',
                'verbose_name_plural': 'Wiadomości',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='api_message_booking_5ca8a6_idx'), models.Index(fields=['sender', 'recipient'], name='api_message_sender__a3289a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Wpłata'), ('payment', 'Płatność za przejazd'), ('withdrawal', 'Wypłata'), ('refund', 'Zwrot'), ('driver_payment', 'Wypłata dla kierowcy')], max_length=20, verbose_name='Typ transakcji')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kwota')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.booking', verbose_name='Rezerwacja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.trip', verbose_name='Przejazd')),
            ],
            options={
                'verbose_name': 'Transakcja',
                'verbose_name_plural': 'Transakcje',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_transac_user_id_f5f95b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Ocena (1-5)')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Komentarz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.booking', verbose_name='Rezerwacja')),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Oceniany')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Oceniający')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.trip', verbose_name='Przejazd')),
            ],
            options={
                'verbose_name': 'Recenzja',
                'verbose_name_plural': 'Recenzje',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reviewed_user', 'created_at'], name='api_review_reviewe_dffd79_idx'), models.Index(fields=['trip', 'reviewer'], name='api_review_trip_id_463117_idx')],
                'unique_together': {('reviewer', 'trip', 'reviewed_user')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_trip_on_favorite_route', 'Nowy przejazd na ulubionej trasie'), ('booking_request', 'Nowa prośba o rezerwację'), ('booking_accepted', 'Rezerwacja zaakceptowana'), ('booking_rejected', 'Rezerwacja odrzucona')], max_length=50, verbose_name='Typ powiadomienia')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('read', models.BooleanField(default=False, verbose_name='Przeczytane')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.favoriteroute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.trip')),
            ],
            options={
                'verbose_name': 'Powiadomienie',
                'verbose_name_plural': 'Powiadomienia',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read'], name='api_notific_user_id_6c29be_idx')],
            },
        ),
    ]
