# Generated by Django 5.2.10 on 2026-01-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_role',
            field=models.CharField(choices=[('driver', 'Kierowca'), ('passenger', 'Pasażer')], max_length=20, verbose_name='Rola użytkownika'),
        ),
    ]
