# Generated by Django 5.2.8 on 2026-01-18 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_preferred_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('accepted', 'Zaakceptowane'), ('rejected', 'Odrzucone'), ('blocked', 'Zablokowane')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Otrzymujący zaproszenie')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='Wysyłający zaproszenie')),
            ],
            options={
                'verbose_name': 'Znajomość',
                'verbose_name_plural': 'Znajomości',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requester', 'status'], name='api_friends_request_a8a73c_idx'), models.Index(fields=['receiver', 'status'], name='api_friends_receive_bc0aee_idx')],
                'unique_together': {('requester', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate_behavior', 'Niewłaściwe zachowanie'), ('harassment', 'Nękanie'), ('no_show', 'Nie pojawienie się'), ('dangerous_driving', 'Niebezpieczna jazda'), ('fraud', 'Oszustwo'), ('other', 'Inne')], max_length=50, verbose_name='Powód')),
                ('description', models.TextField(verbose_name='Opis')),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('under_review', 'W trakcie weryfikacji'), ('resolved', 'Rozwiązane'), ('dismissed', 'Odrzucone')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notatki administratora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data rozwiązania')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='Zgłaszany użytkownik')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Zgłaszający')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='api.trip', verbose_name='Przejazd')),
            ],
            options={
                'verbose_name': 'Zgłoszenie',
                'verbose_name_plural': 'Zgłoszenia',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='api_report_status_2ddde8_idx'), models.Index(fields=['reported_user', 'created_at'], name='api_report_reporte_7cfeed_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Notatka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trusted_marks', to='api.trip', verbose_name='Przejazd')),
                ('trusted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_user_of', to=settings.AUTH_USER_MODEL, verbose_name='Zaufany użytkownik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_by', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik, który dodał do zaufanych')),
            ],
            options={
                'verbose_name': 'Zaufany użytkownik',
                'verbose_name_plural': 'Zaufani użytkownicy',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_trusted_user_id_84d656_idx')],
                'unique_together': {('user', 'trusted_user')},
            },
        ),
    ]
