# Generated by Django 5.2.10 on 2026-01-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_friendship_report_trusteduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_trip_on_favorite_route', 'Nowy przejazd na ulubionej trasie'), ('booking_request', 'Nowa prośba o rezerwację'), ('booking_accepted', 'Rezerwacja zaakceptowana'), ('booking_rejected', 'Rezerwacja odrzucona'), ('driver_message', 'Wiadomość od kierowcy')], max_length=50, verbose_name='Typ powiadomienia'),
        ),
    ]
