# Generated by Django 5.2.8 on 2026-01-06 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20251209_1758'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255, verbose_name='Punkt początkowy')),
                ('end_location', models.CharField(max_length=255, verbose_name='Punkt docelowy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ulubiona trasa',
                'verbose_name_plural': 'Ulubione trasy',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'start_location', 'end_location')},
            },
        ),
    ]
