# Generated by Django 5.2.8 on 2026-01-27 19:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trusteduser',
            name='auto_accept',
            field=models.BooleanField(default=False, verbose_name='Automatyczna akceptacja rezerwacji'),
        ),
        migrations.CreateModel(
            name='RecurringTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255, verbose_name='Punkt początkowy')),
                ('end_location', models.CharField(max_length=255, verbose_name='Punkt docelowy')),
                ('intermediate_stops', models.JSONField(blank=True, default=list, verbose_name='Punkty pośrednie')),
                ('time', models.TimeField(verbose_name='Godzina')),
                ('available_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Liczba dostępnych miejsc')),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena za miejsce')),
                ('frequency', models.CharField(choices=[('daily', 'Codziennie'), ('weekly', 'Co tydzień'), ('biweekly', 'Co dwa tygodnie'), ('monthly', 'Co miesiąc')], max_length=20, verbose_name='Częstotliwość')),
                ('weekdays', models.JSONField(blank=True, default=list, verbose_name='Dni tygodnia (dla weekly)')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data zakończenia (opcjonalnie)')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('last_generated', models.DateField(blank=True, null=True, verbose_name='Ostatnia generacja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cykliczny przejazd',
                'verbose_name_plural': 'Cykliczne przejazdy',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'active'], name='api_recurri_driver__a99e02_idx'), models.Index(fields=['start_date', 'end_date'], name='api_recurri_start_d_a946b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_requested', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notified', models.BooleanField(default=False, verbose_name='Powiadomiony')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='api.trip')),
            ],
            options={
                'verbose_name': 'Lista oczekujących',
                'verbose_name_plural': 'Listy oczekujących',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['trip', 'notified'], name='api_waitlis_trip_id_8a9683_idx')],
                'unique_together': {('trip', 'passenger')},
            },
        ),
    ]
