# Generated by Django 5.2.8 on 2026-01-06 03:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_favoriteroute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Moja trasa', max_length=255, verbose_name='Nazwa szablonu')),
                ('start_location', models.CharField(max_length=255, verbose_name='Punkt początkowy')),
                ('end_location', models.CharField(max_length=255, verbose_name='Punkt docelowy')),
                ('intermediate_stops', models.JSONField(blank=True, default=list, verbose_name='Punkty pośrednie')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Godzina')),
                ('available_seats', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Liczba dostępnych miejsc')),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena za miejsce')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Szablon przejazdu',
                'verbose_name_plural': 'Szablony przejazdów',
                'ordering': ['-created_at'],
            },
        ),
    ]
