# Generated by Django 5.2.8 on 2026-01-06 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_triptemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_trip_on_favorite_route', 'Nowy przejazd na ulubionej trasie')], max_length=50, verbose_name='Typ powiadomienia')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('read', models.BooleanField(default=False, verbose_name='Przeczytane')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.favoriteroute')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Powiadomienie',
                'verbose_name_plural': 'Powiadomienia',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read'], name='api_notific_user_id_6c29be_idx')],
            },
        ),
    ]
