# Generated by Django 5.2.8 on 2026-01-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Powiadomienia włączone'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_trip_on_favorite_route', 'Nowy przejazd na ulubionej trasie'), ('booking_request', 'Nowa prośba o rezerwację'), ('booking_accepted', 'Rezerwacja zaakceptowana'), ('booking_rejected', 'Rezerwacja odrzucona')], max_length=50, verbose_name='Typ powiadomienia'),
        ),
    ]
