# Generated by Django 6.0.1 on 2026-01-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trusteduser_auto_accept_recurringtrip_waitlist'),
        ('api', '0009_booking_paid_at_alter_booking_status_wallet_and_more'),
    ]

    operations = [
    ]
