# Generated by Django 6.0.1 on 2026-01-28 08:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20260128_0941'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Zakończony'),
        ),
        migrations.AddField(
            model_name='trip',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Identyfikator Google'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Treść wiadomości')),
                ('read', models.BooleanField(default=False, verbose_name='Przeczytane')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.booking', verbose_name='Rezerwacja')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Odbiorca')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Nadawca')),
            ],
            options={
                'verbose_name': 'Wiadomość',
                'verbose_name_plural': 'Wiadomości',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='api_message_booking_5ca8a6_idx'), models.Index(fields=['sender', 'recipient'], name='api_message_sender__a3289a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Ocena (1-5)')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Komentarz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.booking', verbose_name='Rezerwacja')),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='Oceniany')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Oceniający')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.trip', verbose_name='Przejazd')),
            ],
            options={
                'verbose_name': 'Recenzja',
                'verbose_name_plural': 'Recenzje',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reviewed_user', 'created_at'], name='api_review_reviewe_dffd79_idx'), models.Index(fields=['trip', 'reviewer'], name='api_review_trip_id_463117_idx')],
                'unique_together': {('reviewer', 'trip', 'reviewed_user')},
            },
        ),
    ]
