# Generated by Django 5.2.8 on 2026-03-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_trip_completed_trip_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Szacowany czas przejazdu (minuty)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='luggage_ok',
            field=models.BooleanField(default=True, verbose_name='Miejsce na bagaż'),
        ),
    ]
